import type { Metadata } from "next";
import { Geist_Mono, Jost } from "next/font/google";

import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";
import "./globals.css";
import NavBar from "@/components/layout/NavBar";
import Client from "./client";
import NextTopLoader from "nextjs-toploader";

const geistSans = Jost({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} ${geistMono.variable} antialiased`}
      >
        <NextTopLoader />
        <Client>
          <div className="relative">
            <NavBar />

            {children}
          </div>
        </Client>
      </body>
    </html>
  );
}
